# Generated by Django 4.2 on 2025-03-04 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0060_ticketnote'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AddField(
            model_name='useractivity',
            name='employee_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='skill_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
