# Generated by Django 4.2 on 2025-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_useractivity_date_useractivity_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
