# Generated by Django 4.2 on 2025-03-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_useractivity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='process_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
