# Generated by Django 4.2 on 2025-03-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_useractivity_process_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='active_window_title',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='cpu_usage',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='memory_usage',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='process_name',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='process_start_time',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='idle_duration',
            field=models.FloatField(default=0),
        ),
    ]
