# Generated by Django 4.2 on 2025-03-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_remove_useractivity_active_window_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='activityreport',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-date', '-idle_start'], 'verbose_name_plural': 'User Activities'},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='tracking_us_email_cc2120_idx',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='is_idle',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='time_of_day',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='idle_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='idle_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='email',
            field=models.EmailField(blank=True, default=None, help_text="User's email address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='idle_duration',
            field=models.FloatField(default=0, help_text='Idle duration in minutes'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['email', 'date'], name='tracking_us_email_a4dab4_idx'),
        ),
        migrations.DeleteModel(
            name='ActivityReport',
        ),
    ]
