# Generated by Django 4.2 on 2025-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_alter_activityreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-activity_date', '-idle_start_time'], 'verbose_name_plural': 'User Activities'},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='tracking_us_email_a4dab4_idx',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='date',
            new_name='activity_date',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='idle_end',
            new_name='idle_end_time',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='idle_start',
            new_name='idle_start_time',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='idle_duration',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='total_idle_minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['email', 'activity_date'], name='tracking_us_email_ef34c2_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user_login'], name='tracking_us_user_lo_4c2370_idx'),
        ),
    ]
