# Generated by Django 4.2 on 2025-03-13 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0009_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_active_time', models.DurationField()),
                ('total_idle_time', models.DurationField()),
                ('activity_summary', models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'User Activities'},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='tracking_us_email_ef34c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='tracking_us_user_lo_4c2370_idx',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='activity_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='total_idle_minutes',
            new_name='idle_duration',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='idle_end_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='idle_start_time',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_login',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='is_idle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='time_of_day',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['email', 'date', 'time_of_day'], name='tracking_us_email_cc2120_idx'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='activityreport',
            unique_together={('user', 'date')},
        ),
    ]
