# Generated by Django 4.2 on 2025-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_activityreport_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='idle_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
