# Generated by Django 4.2 on 2025-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_useractivity_idle_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
