# Generated by Django 4.2 on 2024-12-09 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='call_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='call_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='call_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='call_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
