# Generated by Django 4.2 on 2024-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_ticket_call_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='call_timer_started_by_call',
            field=models.BooleanField(default=False),
        ),
    ]
