# Generated by Django 4.2 on 2024-12-27 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_delete_callstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='individual_time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
