# Generated by Django 4.2 on 2024-12-30 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_ticket_individual_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_break_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
