# Generated by Django 4.2 on 2025-01-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='note_text',
        ),
    ]
