# Generated by Django 4.2 on 2025-01-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_rename_text_note_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_call_note',
            field=models.TextField(blank=True),
        ),
    ]
