# Generated by Django 4.2 on 2025-01-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_clientcallnote_remove_call_call_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paused_ticket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
