# Generated by Django 4.2 on 2025-01-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_ticket_paused_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='paused_ticket_id',
        ),
    ]
