# Generated by Django 4.2 on 2025-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_remove_ticket_paused_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_on_call',
            field=models.BooleanField(default=False),
        ),
    ]
