# Generated by Django 4.2 on 2025-01-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_employeeprofile_is_on_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paused_by_other_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='paused_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
