# Generated by Django 4.2 on 2025-01-21 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0039_ticket_paused_by_other_call_ticket_paused_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCallQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(default='levelone@example.com', max_length=254)),
                ('client_email', models.EmailField(max_length=254)),
                ('cc_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('note', models.TextField()),
                ('call_start_time', models.DateTimeField(auto_now_add=True)),
                ('call_end_time', models.DateTimeField(blank=True, null=True)),
                ('ticket_created', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_call_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
