# Generated by Django 4.2 on 2025-01-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0041_newcallquery_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='call_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcallquery',
            name='call_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
