# Generated by Django 4.2 on 2025-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0042_employeeprofile_call_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcallnote',
            name='call_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
