# Generated by Django 4.2 on 2025-01-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0044_ticketnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
