# Generated by Django 4.2 on 2025-01-28 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0045_ticket_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketnotification',
            name='last_notification_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketnotification',
            name='notification_counter',
            field=models.IntegerField(default=0),
        ),
    ]
