# Generated by Django 4.2 on 2025-01-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0046_ticket_acknowledged_at_ticket_is_acknowledged_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
