# Generated by Django 4.2 on 2025-01-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0050_alter_ticket_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyStats',
        ),
    ]
