# Generated by Django 4.2 on 2025-01-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0051_delete_dailystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='environment',
            field=models.CharField(choices=[('postiefs', 'Postiefs'), ('aws', 'AWS'), ('azure', 'Azure'), ('oracle', 'Oracle'), ('google', 'Google')], default='postiefs', help_text='Select the cloud environment', max_length=50),
        ),
    ]
