# Generated by Django 4.2 on 2025-01-31 07:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0053_ticketalert'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketalert',
            unique_together={('ticket', 'user')},
        ),
    ]
