# Generated by Django 4.2 on 2025-02-03 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0054_alter_ticketalert_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('exceeded', 'Exceeded SLA'), ('pre_notification', '5-min Warning'), ('pending', 'Pending')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('last_notification_time', models.DateTimeField(auto_now_add=True)),
                ('notification_count', models.IntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_notifications', to='employee.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ticket', 'user', 'notification_type')},
            },
        ),
        migrations.RemoveField(
            model_name='ticketnotification',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='TicketAlert',
        ),
        migrations.DeleteModel(
            name='TicketNotification',
        ),
    ]
