# Generated by Django 4.2 on 2025-02-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0055_unifiednotification_remove_ticketnotification_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiednotification',
            name='notification_type',
            field=models.CharField(choices=[('exceeded', 'Exceeded SLA'), ('pre_notification', '5-min Warning'), ('pending', 'Pending'), ('assigned', 'Ticket Assigned'), ('created', 'Ticket Created')], max_length=20),
        ),
    ]
