# Generated by Django 4.2 on 2025-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0056_alter_unifiednotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('waiting_on_customer', 'Waiting on Customer'), ('initial_response', 'Initial Response'), ('on_hold', 'On Hold')], max_length=50),
        ),
    ]
