# Generated by Django 4.2 on 2025-02-11 10:18

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0058_workreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB)', null=True, upload_to='profile_pictures/', validators=[employee.models.validate_image_size]),
        ),
    ]
