# Generated by Django 4.2 on 2025-02-19 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0059_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('creation', 'Creation Note'), ('reassignment', 'Reassignment Note'), ('call', 'Call Note'), ('client_call', 'Client Call Note'), ('general', 'General Note')], max_length=50)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_duration', models.DurationField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notes', to='employee.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
