# Generated by Django 4.2 on 2025-03-14 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0060_ticketnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField()),
                ('is_idle', models.BooleanField(default=False)),
                ('idle_duration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='total_idle_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
