# Generated by Django 4.2 on 2025-03-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0062_delete_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_idle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_break', 'On Break'), ('idle', 'Idle'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
