# Generated by Django 4.2 on 2025-03-18 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0064_employeeprofile_reporting_manager_ondutyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondutyrequest',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), null=True),
        ),
        migrations.AddField(
            model_name='ondutyrequest',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
