# Generated by Django 4.2 on 2025-04-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0067_ticket_is_scheduled_ticket_scheduled_assign_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='scheduled_assign_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='scheduled_assign_to',
        ),
    ]
